name: Deploy Angular to EC2 (Nginx - Production)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Setup Node
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # 3. Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4. Build Angular app
      - name: Build Angular app
        run: npm run build -- --configuration production

      # 5. Verify build (debug)
      - name: Verify build output
        run: ls -R dist/ec2-cicd-app/browser

      # 6. Clean server folder
      - name: Prepare EC2 directory
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo rm -rf /var/www/angular-app/*
            sudo mkdir -p /var/www/angular-app

      # 7. Copy ONLY Angular build folder
      - name: Copy build to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "dist/ec2-cicd-app/browser"
          target: "/home/ubuntu"

      # 8. Move correct files to Nginx
      - name: Deploy to Nginx
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo cp -r /home/ubuntu/dist/ec2-cicd-app/browser/* /var/www/angular-app/

            sudo chown -R www-data:www-data /var/www/angular-app
            sudo chmod -R 755 /var/www/angular-app

            sudo systemctl restart nginx

            # cleanup uploaded build
            rm -rf /home/ubuntu/dist