name: Deploy Angular to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Setup Node
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 24

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Build Angular app
      - name: Build Angular app
        run: npm run build -- --configuration production

      # 5. Copy build to EC2
      - name: Copy files to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "dist/ec2-cicd-app/browser/*"
          target: "/home/ubuntu/Ec2cicd"

      # 6. Restart app on EC2
      - name: Restart app on EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd Ec2cicd

            npm install -g serve

            pm2 delete angular-app || true
            pm2 start "serve -s . -l 3000" --name angular-app

            pm2 save