name: Deploy Angular to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 24

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: npm run build -- --configuration production

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd Ec2cicd
            git pull origin main
            npm install
            npm install -g serve
            npm run build -- --configuration production
            pm2 restart angular-app
